trying cache from sdk

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -2,6 +2,50 @@ name: indy-node-build
 on: [ push, pull_request ]
 
 jobs:
+  workflow-setup:
+    runs-on: ubuntu-latest
+    outputs:
+      CACHE_LINT_IMAGE: ${{ steps.cache.outputs.CACHE_LINT_IMAGE }}
+    steps:
+      - name: Git checkout
+        uses: actions/checkout@v2
+      - name: Set outputs
+        id: cache
+        run: |
+          LINT_DOCKERFILE_HASH=${{ hashFiles('.github/workflows/build/Dockerfile') }}
+          echo "::set-output name=CACHE_KEY_LINT::$LINT_DOCKERFILE_HASH"
+          echo "::set-output name=DOCKER_IMG_NAME_LINT::lint:$LINT_DOCKERFILE_HASH"
+           
+  build-lint-image:
+    needs: workflow-setup
+    runs-on: ubuntu-latest
+    env:
+      DOCKER_BUILDKIT: 1
+      CACHE_KEY_LINT: ${{ needs.workflow-setup.outputs.CACHE_KEY_LINT }}
+      DOCKER_IMG_NAME_LINT: ${{ needs.workflow-setup.outputs.DOCKER_IMG_NAME_LINT }}
+    steps:
+      - name: Git checkout
+        uses: actions/checkout@v2
+      - name: Try load from cache.
+        id: cache-image-lint
+        uses: actions/cache@v2
+        with:
+          path: /tmp/imgcache
+          key: ${{ env.CACHE_KEY_LINT }}
+      - name: If NOT found in cache, build and cache image.
+        if: steps.cache-image-lint.outputs.cache-hit != 'true'
+        run: |
+          docker build -t "$DOCKER_IMG_NAME_LINT" -f .github/workflows/build/Dockerfile lint
+          mkdir -p /tmp/imgcache
+          docker save "$DOCKER_IMG_NAME_LINT" > /tmp/imgcache/img_lint.rar
+      - name: Load image from cache
+        run: |
+          docker load < /tmp/imgcache/img_lint.rar
+      - name: Verify lint image was loaded
+        run: |
+          docker image ls --format "{{.Repository}}:{{.Tag}}" | grep "$DOCKER_IMG_NAME_LINT" || { echo "Image $DOCKER_IMG_NAME_LINT was not found!" ; exit 1; }
+
+
   decorator-checks:
     name: Run decorator checks
     needs: lint
@@ -77,12 +121,29 @@ jobs:
 
   lint:
     name: Lint
-    runs-on: ubuntu-18.04
-    #TODO: move this to hyperledger?
-    container: m00sey/indy-node-lint:latest
+    runs-on: ubuntu-latest
+    needs:
+      - workflow-setup
+      - build-lint-image
+    env:
+      DOCKER_BUILDKIT: 1
+      CACHE_KEY_LINT: ${{ needs.workflow-setup.outputs.CACHE_KEY_LINT }}
+      DOCKER_IMG_NAME_LINT: ${{ needs.workflow-setup.outputs.DOCKER_IMG_NAME_LINT }}
     steps:
-      - name: Check out code
+      - name: Git checkout
         uses: actions/checkout@v2
-
+      - name: Load lint image
+        id: load-cached-lint-image
+        uses: actions/cache@v2
+        with:
+          path: /tmp/imgcache
+          key: ${{ env.CACHE_KEY_LINT }}
+      - name: If no cached image found
+        if: steps.load-cached-lint-image.outputs.cache-hit != 'true'
+        run: echo "ERROR == Expected to find image from cache $CACHE_KEY_LINT"; exit -1
+      - name: Load image from cache
+        run: docker load < /tmp/imgcache/img_lint.rar
       - name: flake8
-        run: python3 -m flake8
+        run: | 
+          docker run --rm -i --name lint  bash -c 'python3 -m flake8'
+          
